### ISSUE TITLE
Error Mysql Pool

### ISSUE THREAD

**Issue by Lautarotetamusa** [Lautarotetamusa/Epublit#15]
app-1  | TypeError: Cannot read properties of undefined (reading 'once')
app-1  |     at /app/node_modules/mysql2/lib/pool.js:154:29
app-1  |     at /app/node_modules/mysql2/lib/pool.js:49:37
app-1  |     at processTicksAndRejections (node:internal/process/task_queues:77:11)

**Comment by Lautarotetamusa** [comment]
app-1  | [server]: GET /consignacion
app-1  | TypeError: Cannot read properties of undefined (reading 'once')
app-1  |     at /app/node_modules/mysql2/lib/pool.js:154:29
app-1  |     at /app/node_modules/mysql2/lib/pool.js:49:37
app-1  |     at processTicksAndRejections (node:internal/process/task_queues:77:11)
app-1  | [nodemon] app crashed - waiting for file changes before starting...
